(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/emacs-conf/lisp/auto-complete/dict")
(add-to-list 'ac-user-dictionary-files "~/emacs-conf/lisp/auto-complete/dict/my-dictionary")
(ac-config-default)
(setq ac-menu-height 20)
(setq ac-auto-start 1)
