(define-key global-map "\C-h" 'backward-delete-char)
(define-key global-map (kbd "C-`") 'scroll-n-lines-behind)
(define-key global-map "\C-z" 'scroll-n-lines-ahead)
(define-key global-map "\C-o" 'goto-line)
(define-key global-map "\C-c;" 'comment-region)
(define-key global-map "\C-c:" 'uncomment-region)
(define-key global-map "\C-cr" 'replace-string)
(define-key global-map (kbd "C-j") 'newline-and-indent)
(define-key global-map "\M-s" 'other-window-or-split)
(define-key global-map "\M-c" 'helm-filelist)
(define-key global-map "\M-q" 'helm-grep)
(define-key global-map "\M-g" 'quickrun)
(define-key global-map "\C-c\C-i" 'dabbrev-expand)
(define-key global-map "\C-x\C-p" 'my-popup-flymake-display-error)
(define-key global-map "\C-x\C-i" 'indent-region)
(define-key global-map (kbd "C-S-o") 'helm-recentf)
(define-key global-map (kbd "C-S-j") 'enlarge-window)
(define-key global-map (kbd "C-S-k") 'enlarge-window-horizontally)
(define-key global-map (kbd "C-S-q") 'toggle-global-whitespace-mode)
(define-key global-map (kbd "C-S-u") 'undo)
(define-key global-map (kbd "M->") 'pop-tag-mark)
(define-key global-map (kbd "C-c g") 'helm-git-grep)
(define-key global-map (kbd "C-c j") 'helm-ls-git-ls)
(define-key global-map (kbd "C-x c g") 'pop-tag-mark)

(define-key c++-mode-map "\C-c:" 'uncomment-region)
;; (define-key dired-mode-map "\M-s" 'other-window-or-split)
