(define-key global-map "\C-h" 'backward-delete-char)
(define-key global-map (kbd "C-o") 'scroll-n-lines-behind)
(define-key global-map "\C-z" 'scroll-n-lines-ahead)
(define-key global-map "\C-c;" 'comment-region)
(define-key global-map "\C-c:" 'uncomment-region)
(define-key global-map "\C-cr" 'replace-string)
(define-key global-map (kbd "C-j") 'newline-and-indent)
(define-key global-map "\C-x\C-i" 'indent-region)
(define-key global-map "\C-co" 'helm-recentf)
