(define-key global-map "\C-h" 'backward-delete-char)
(define-key global-map "\C-q" 'scroll-n-lines-behind)
(define-key global-map "\C-z" 'scroll-n-lines-ahead)
(define-key global-map "\C-o" 'goto-line)
(define-key global-map "\C-c;" 'comment-region)
(define-key global-map "\C-c:" 'uncomment-region)
(define-key global-map "\C-cr" 'replace-string)
(define-key global-map "\M-s" 'other-window-or-split)
(define-key global-map "\M-c" 'anything)
(define-key global-map "\C-c\C-i" 'dabbrev-expand)
(define-key global-map "\C-x\C-i" 'indent-region)
(define-key global-map (kbd "C-S-o") 'recentf-open-files)
(define-key global-map (kbd "C-S-j") 'enlarge-window)
(define-key global-map (kbd "C-S-k") 'enlarge-window-horizontally)
(define-key global-map (kbd "C-S-p") 'increase-opacity)
(define-key global-map (kbd "C-S-n") 'decrease-opacity)
(define-key global-map (kbd "C-S-q") 'toggle-global-whitespace-mode)
(define-key global-map (kbd "C-S-t") 'toggle-indent-tabs-mode)
(define-key global-map (kbd "C-S-u") 'undo)
(define-key global-map (kbd "M->") 'pop-tag-mark)

;; (define-key dired-mode-map "\M-s" 'other-window-or-split)
